### ISSUE TITLE
Autocompletion doesn't work unless suggestion selected

### ISSUE THREAD

**Issue by nh2** [frappe/books#126]
![image](https://user-images.githubusercontent.com/399535/81249172-4b010c80-901e-11ea-92ef-f11a5ccf2b83.png)

Trying to **Save** gets me a popup `Value missing for "items"`, and then it throws away all I've typed as the line items so far.

Using `0.0.3-beta.12-binary` via AppImage on Linux.

**Comment by nh2** [comment]
I think it happens when you just type something into the **Item** cell, without clicking `Create` afterwards to create a dedicated standalone item in the side bar.

It is not obvious that you _have_ to click `Create`; if that is required it should probably tell you, instead of discarding the entire invoice contents.

**Comment by 18alantom** [comment]
Steps to reproduce
1. Create a new invoice
2. Add row
3. Enter the item name, don't click the item from the drop-down.
4. Click outside the text field
5. Save

Expected behavior: 
- When the focus is lost from the Item text field, it should auto-complete the other values by matching with an existing item.
- Clicking on the item name shouldn't be required.

**Comment by 18alantom** [comment]
Fixed in these [[one](https://github.com/frappe/books/commit/9fa7968fe279fa295478ac43562042631cf9ac9c), [two](https://github.com/frappe/books/commit/f4b14bc0da3d397d9fb2ff05f2c3f9dea90f5ee5)] commits
