### ISSUE TITLE
How to include description & customer GST in invoice

### ISSUE THREAD

**Issue by parthi2929** [frappe/books#173]
Firstly, thank you for such great products. The apps look very neat, simple to start for beginners like me. I was impressed by simplicity of erpnext, but wondering for personal do I have to pay hefty amount for VM and to my delight, you have frappe books for it. 

I was trying it and found below issues. Kindly help. 

* I could not find a way to include Item description in invoices. I included the description when creating the items, but they do not show up in invoice and I could find no way to include that. 
* I could not find a way to include customer's GST info in customer address space. I need to include that in my invoice. Any reason customer's GST info not included in their detail form?

![image](https://user-images.githubusercontent.com/11896263/94231036-d5d89a00-ff20-11ea-9012-f40dcfe07819.png)
* Also is there a possibility to preview the final invoice form without submitting? Every time I submit and have to view, adding these tries to the ledger entries. 
* There is a minor bug, even if I include no comma in address, between city and state, there comes 2 comma lines as shown below always (in invoice)
![image](https://user-images.githubusercontent.com/11896263/94232392-7fb92600-ff23-11ea-9100-3413d581bcbd.png)
* Also please include option to place a custom image anywhere on sales invoice. Customer demands it.

**Comment by ankitsinghaniyaz** [comment]
GST number is a must I think. I'll try to fork and check if it's easy to add it.

**Comment by ankitsinghaniyaz** [comment]
@parthi2929 Thanks for such detailed feedback.

We are preparing a new release of the Frappe Books and we have addressed some of your issues.

1. GST information can now be added for customers(buyer + seller)
2. We still don't have a invoice template that can support the item description, so that will not be supported in this release but definitly we'll work on this in future. I'm going to create a card for this in our issues board which you can follow.
3. We will not support printing without submitting, unless we see a reason to that. The root problem in this case is the ledger trail which we are fixing. So it will remove the unwated clutter and only show the latest/correct values.
4. The address bug with unwanted , has been resolved
5. Image also we might not be able to do it in the current sprint but based on what more user say about this we will prioritize this in future.

**Comment by 18alantom** [comment]
Closing because this is a group of several issues and requests; created a new issue for the feasible suggestion in this.
