### ISSUE TITLE
Option for precision

### ISSUE THREAD

**Issue by manomayholdings** [frappe/books#185]
Hello Contributors,
I Have Found That During Product Add Process My Product Price is 0.567 Rs Per Item So Book rounded Off to 0.58 Rs But as No Of Product is 120000 So 0.567 - 0.58 = 0.013
So 0.013 X 120000 = 1560 Difference*

So Can You Share Me How We Can Add Amount more than 2 Decimal or As Per Choice For All Books.

THANKS
![0 576](https://user-images.githubusercontent.com/25424914/103221645-1f35ec80-4949-11eb-90f4-5e2a83c88703.png)

**Comment by piyushsinghania** [comment]
I appreciate your observation. And I would like to add up by asking whether you entered 0.576 or 0.567 in the Rate section? As I can see in the above image you might have entered the wrong rate (In the section where you are adding the rate of your product, I see it to be 0.576, which if rounded is 0.58). While in the calculations above you are using the rate of the product as 0.567 and hence a difference of 0.013 is arising rather than 0.003 which in turn would have reduced the difference significantly.

In my mind it can be fixed by changing the decimal points to get the desired value.

**Comment by 18alantom** [comment]
Books rounds of values to the second decimal place, need to add a _precision_ setting.

**Comment by 18alantom** [comment]
Closing cause: https://github.com/frappe/books/pull/268 merged
