### ISSUE TITLE
[Question] Next release date

### ISSUE THREAD

**Issue by MountBlu** [frappe/books#259]
Hello, huge fan of ERPNext but it's overkill for my business. I'm really interested in FrappeBooks and it seems perfect for my needs. Any idea when is the new build will be released? Because the latest build is still from early 2020 and it has this "SetupWizard null already exists" error which I believe is already fixed in the latest code.

**Comment by 18alantom** [comment]
@MountBlu all the changes and fixes for version 0.0.4 (upcoming release) are ready. We are waiting for certificates to be issued (for code signing) so that when someone installs Frappe Books it doesn't show as untrusted software.

The certificate provider has been holding us up for nearly a week now, else it would have been out by now.

**Comment by 18alantom** [comment]
(will close on release)

**Comment by 18alantom** [comment]
New release is out: https://github.com/frappe/books/releases/tag/v0.0.4-beta.0
