### ISSUE TITLE
can't create new file on release 0.0.3.beta.9 when selecting country with spaces

### ISSUE THREAD

**Issue by ddimmich** [frappe/books#267]
<img width="536" alt="Screenshot 2021-12-02 at 12 16 20" src="https://user-images.githubusercontent.com/64750/144383778-d958a355-55c3-4887-ac17-5e01c592033e.png">

**Comment by 18alantom** [comment]
@ddimmich 0.0.3.beta.9 has several bugs.

You can either 
1. Try [0.0.3-beta.13](https://github.com/frappe/books/releases/tag/v0.0.3-beta.13) but this too has several bugs and I doubt this issue is fixed in it.
2. Wait for 0.0.4-beta.0 which is to be [released soon](https://github.com/frappe/books/issues/259).
