### ISSUE TITLE
Installation Issue: Operation didn't completed successfully because file contains virus or potential unwanted software.

### ISSUE THREAD

**Issue by asharamseervi** [frappe/books#282]
Hi @18alantom, you just released v0.0.4-beta.2.

I'm facing some issues regarding installation, might you forgot to sign binaries or whatever! Kindly fix & update binaries!

Screenshot:

![frappe-books-install-issue](https://user-images.githubusercontent.com/5942572/146515033-d3e1977d-6588-48bb-8a2b-e0ab504438ab.png)

**Comment by 18alantom** [comment]
@asharamseervi thanks for pointing it out; will take a look.

Signing shouldn't have been the issue since CI takes care of it. In this step: https://github.com/frappe/books/runs/4557274178?check_suite_focus=true#step:7:98 the windows NSIS installer was signed.

Can you check if the [portable](https://github.com/frappe/books/releases/download/v0.0.4-beta.2/Frappe-Books-0.0.4-beta.2.exe) version works without the error?

I'll try any figure out why this happened; shouldn't happen in the next release.

**Comment by asharamseervi** [comment]
Yes, portable version worked.

But as expected installer should be working, as this release contains many improvement/fixes! You should release v0.0.4-beta.3 with fix. If not planning for v0.0.4-beta.3, can you estimate when v0.0.5-beta.0 will be releasing?

**Comment by 18alantom** [comment]
@asharamseervi I double-checked the setup installer for v0.0.4-beta.2 on a different system than what I had used earlier when releasing the version.

It **did not give any virus related warnings** and was **installed correctly**. I was able to check the code-sign certificate too.

The OS details are:
```
OS Edition: Windows 10 Home Single Language
Version:    21H1
OS Build:   19043.1415
```

Besides this, **all Windows Defender settings were switched on** (primarily App & browser control), the system was also **running Quick Heal Antivirus**.

Can you provide some relevant details as to why this is occurring on your system? Is it because of antivirus software? What are your OS details?

Here are some pictures from smart-screen on opening the installer (wasn't able to screenshots of smart-screen):
![IMG_20220111_104846](https://user-images.githubusercontent.com/29507195/148886690-2ac4804b-978e-428d-b179-deee4357f527.jpeg)

![IMG_20220111_104915](https://user-images.githubusercontent.com/29507195/148886721-1907f279-80cb-4c57-838a-ad42c2f8bcc6.jpeg)

**Comment by 18alantom** [comment]
Update: @piyushsinghania  was able to replicate it. Shows as a virus on download and smart-screen blocks the install.

**Comment by 18alantom** [comment]
virus report says there's a trojan in the installer (detected only by Microsoft): https://www.virustotal.com/gui/file/9190c6d545fd2455253d6d6c28c97702ea81d07ab724cf46e476427a453bcebe
![Screenshot 2022-01-11 at 16 20 03](https://user-images.githubusercontent.com/29507195/148929331-22ed984f-d01f-4c4e-b156-7030bcd9abe8.png)

built locally (not signed), this doesn't have any false positives:
https://www.virustotal.com/gui/file/95a6802b5c82e4abe21c981d0468ae8be24a13b18d96e18082cb5de4dd80b2bf

**Comment by asharamseervi** [comment]
Hi @18alantom In case of virus, even it's false positive, should be investigated and fixed at earliest possible! That's the rule of thumb!

**Comment by 18alantom** [comment]
Obligatory update: tried building and code signing the windows binary locally. No issues found locally or on [VirusTotal](https://www.virustotal.com/gui/file/4ed7deb80245634d4157c98c6b75890329ecb2d62d6aeff34e67167dd32271fd?nocache=1).

False-positive should mostly not be there in the next release.

Will double-check (CI publish binary) once I get CI fixed, as of now it's throwing some Visual Studio related errors due to `node-gyp`.

**Comment by 18alantom** [comment]
Windows binaries and related files have been updated for [0.0.4-beta.2](https://github.com/frappe/books/releases/tag/v0.0.4-beta.2), setup file shouldn't throw a false positive I've checked on VirusTotal.
