### ISSUE TITLE
Why do i have Dependency not found fs/promises

### ISSUE THREAD

**Issue by Helkyd** [frappe/books#316]
Hi,
After cloning a fresh Books from source and going through **https://github.com/frappe/books/issues/264**
In which i have done **yarn upgrade frappejs** and was working...
Now when doing yarn build returns the below error!
![image](https://user-images.githubusercontent.com/20396898/150072313-9ed56a21-454f-4b03-8e60-bf24a1d3c43d.png)

**Comment by 18alantom** [comment]
It probably isn't there in the version of `node` you are using (FB requires v16.13.1)

A cursory search leads to this: https://github.com/SAP-samples/hana-developer-cli-tool-example/issues/57 Where it was due to an incorrect node version.

Let me know if this isn't the case, else will close the issue soon.

**Comment by Helkyd** [comment]
Funny because all I did was clone, yarn and yarn build... I see on the
package.json engine version node 16.13.1 and yarn 1.22.17

So what am I not doing to get the build running?

**Comment by 18alantom** [comment]
What's the output you get on running:
```bash
node --version
```

**Comment by Helkyd** [comment]
> 

![image](https://user-images.githubusercontent.com/20396898/150116781-557fd17a-0baa-4f72-a996-2bedeb6b4541.png)

**Comment by 18alantom** [comment]
Hmmm, this is pretty strange 🤨  node 16 should be having `fs/promises`.

What do you get when you try importing it in the `node` REPL?

<img width="371" alt="Screen Shot 2022-01-19 at 17 29 23" src="https://user-images.githubusercontent.com/29507195/150125466-74dbe8e8-bb9e-4803-855b-e4e46d1085ec.png">

_(ss 👆 for reference)_

**Comment by Helkyd** [comment]
I did get that too... :) but when doing yarn build returns the error on babel and cache-loader

This dependency was not found:

* fs/promises in ./node_modules/@vue/cli-plugin-babel/node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/@vue/cli-plugin-babel/node_modules/thread-loader/dist/cjs.js!./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib!./node_modules/@vue/cli-service/node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/@vue/cli-service/node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&

**Comment by Helkyd** [comment]
I have done following process:
Cloned again books
Changed on **backgroup.js and App.vue** the **"import fs from 'fs/promises';"** to **"import fs from 'fs';"**

1    Deleted the node_modules directory & yarn.lock files
2   Added "webpack": **"=4.44.2"** (changed ^ to =) dev dependencies in package.json file as per this post.
3    Ran npm i --force command.
4    Then ran npm run electron:serve command.

After all did yarn build and was Ok.

**Comment by 18alantom** [comment]
Changing to `'fs'` from `'fs/promises'` without changing the usage will mostly lead to bugs. I'm glad you got it running but the underlying issue is still unclear to me, you also mentioned that this occurred on a fresh clone 🧐

Does this link and serve flow (https://github.com/frappe/books/issues/315) work for you?

**Comment by Helkyd** [comment]
So far no other bugs regarding to using 'fs' but of course will check...
Regarding (**[#315](url)**) i did not use **yarn upgrade frappejs**  on the last clean clone code because when doing so and without adding the webpack 4.44.2 it will use the 5.61.0 from frappejs that was creating some issues with the forms i have changed to suit locally.

But of course during the week will give a try following that and see if fs or fs/promises throws bugs.

**Comment by 18alantom** [comment]
Ah alright; if you get the time, do check once (and let me know) whether that sequence of steps runs without any issues. One of the changes that may cause an issue is switching `sqlite3` to the vscode fork.

But since build and publish scripts (CI/CD) are running without issues I'm assuming everything's alright.

Closing since you have resolved the issue using `npm`

**Comment by Helkyd** [comment]
For sure I will.. Regarding  sqlite3 I had to create a windows 8.1 and
compile from there to skip the sqlite3 error of not being a 32bit
application...
