### ISSUE TITLE
Customizing numbering series

### ISSUE THREAD

**Issue by bynicolas** [frappe/books#327]
Is it possible to customize the invoice numbering series (and other number series as well). I see the defaults in the SQLite DB table (`SingleValue`) and in the DocType js file, but it seems that it's not possible to edit that option in the settings UI panel. 

Changing it directly into the DB is overriden by the defaults each time.

If it's not possible, then I would like to make this an official request (enabling UI configuration of number series).

Thanks

**Comment by 18alantom** [comment]
This was in the roadmap, bumping it up; should be out 2 releases down.

**Comment by mBilG** [comment]
I second this.. Would be very helpful to be able to customize the numbering

**Comment by ankitsinghaniyaz** [comment]
This is a more important feature than I assumed previously. Recent had a genuine use case for this.

Wanted to use FB for my dad's business but couldn't. Why?

Because he was creating invoices on paper. Now if I have to switch to a tool. I have to have the invoice start at the same sequence. Cannot use another series or format midst of a financial year.

Also have a couple of suggestions for the invoice. Will create an issue for that.

**Comment by 18alantom** [comment]
I've merged this feature: https://github.com/frappe/books/pull/359 it'll be included in the Friday release :)
