### ISSUE TITLE
[Enhancement]: When setting up in Canada chart of accounts is automatically setup in French without giving any other options.

### ISSUE THREAD

**Issue by dj12djdjs** [frappe/books#345]

**Comment by 18alantom** [comment]
Will add Selection on Setup and close this.

**Comment by 18alantom** [comment]
Hey, I've added CoA selection but for Canada, in fixtures as of now there's no English CoA ([ref](https://github.com/frappe/books/blob/master/fixtures/verified/ca.json)), it'll have to be contributed.

As a fallback, I suppose Standard CoA can be used.

**Comment by TimRyanKaslovia** [comment]
I can provide a Canadian English CofA if you can provide the data format to be used for it.

**Comment by 18alantom** [comment]
Thank you :)

The CoAs are in `json`, with three fields:
```javascript
{
  "countryCode": "[two letter country code]",
  "name": "[CoA name]",
  "tree": {
    // Accounts
  }
}
```

Here's the Canadian French CoA for reference: [ca.json](https://github.com/frappe/books/blob/master/fixtures/verified/ca.json)

Since on inclusion of the Canadian English CoA, there'll be two `ca.json`, locale codes can be used for the file name and `countryCode`:
- English: `en-CA`
- French: `fr-CA`
