### ISSUE TITLE
Invoice serial number chnage not reflecting on the list view

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [frappe/books#378]
Steps to reproduce:

1. Create a new database
2. Create a customer
3. Create an item
4. Create a draft invoice >> save
5. Now edit the invoice to create a new invoice number sequence and select it >> save
6. The new invoice sequence is selected in the invoice but the list view still shows SINV-0001

Adding some screenshots
![image](https://user-images.githubusercontent.com/11331989/161488180-18bdaeb4-4a30-4b74-b2d7-02391fe6a0e7.png)
![image](https://user-images.githubusercontent.com/11331989/161488295-4773c4e7-bf1e-4d64-b9ca-dde5ac0241c9.png)

**Comment by 18alantom** [comment]
For now, I'm removing the changing of Number Series after saving.

Saving the change breaks a lot of things (mainly cause of orphaned child table rows) and requires refactoring some db code.  Since the security change involves this, doing it separately is a bit redundant so will raise a proper fix later.

**Comment by 18alantom** [comment]
Fix [commit](https://github.com/frappe/books/commit/ceb45b58b7ee28bb6f330ab579b3d9c7599f9776)
