### ISSUE TITLE
Item Master Merge as One

### ISSUE THREAD

**Issue by Muzzy73** [frappe/books#471]
Instead if having 3 Item Master it would be better to follow ERPNext method of having 1 item master. Future development of stock and batch will be easier if this is done at early stage.

**Comment by 18alantom** [comment]
@Muzzy73 there is only one Item master similar to Party and Payment.

All three of these are shown in different places depending on certain fields. This is for convenience.

For example, for Items, it is the **For** field. [docs](https://docs.frappebooks.com/entries/items.html)

I'll be allowing the editing of this field so that a Sales Item can be marked for Both too, allowing for Purchases.
