### ISSUE TITLE
Return Issues

### ISSUE THREAD

**Issue by mraniyah** [frappe/books#717]
Hi, first of all... thanks for your nice project dears.
I have encountered some problems and here are details...

My main currency is USD and I have made an invoice with IQD. All okey until here but when I make shipment for this invoice, it converts the IQD amount to USD and basically if an item has 1 USD price it will be converted to 1540$ while doing the shipment and it corrupts all the reporting data.

Second, when I return an item, in inventory > stock balance > Out Qty. will remain same and does not change even incase of returned item.

third issue is, when I login between two databases,  the inventory stock will stuck and does not change and I have to restart the app to do that.

forth, in accounting systems... usually I should able to edit the invoice even after the shipment if invoice status was marked as unpaid. because sometimes, when you get the money from customers, customer may pay less than the amount you made the invoice and in this case I need to return stocks and cancel this invoice and make new invoice and send stocks again.

**Comment by 18alantom** [comment]
**Point 1**

Your main currency is USD and you have made invoice in IQD. If the item price is 1 USD, the invoice created will be for 1540 IQD (assuming 1 USD = 1540 IQD) and when you create a shipment from the invoice (using Create > Shipment), the shipment created is for 1 USD.

It seems to be working as expected for me: 

https://github.com/frappe/books/assets/29507195/fd5329fa-5b27-4622-a0b1-901e1cbdc953



**Point 2**

This is expected behaviour:
1. If your inventory is 3.
2. Shipment is created for 1.
3. Stock return is created for Shipment

Then In Qty. Will be 4 and out quantity will be 1.


**Point 3**

Can you give me steps to replicate? I tried switching between two databases and faced no issues while loading the Stock Ledger and the Stock Balance report.


**Point 4**

If the customer pays less and you would like to mark the invoice as paid you can enter the difference in the Write Off field, this way the amount that was not paid will get accounted.

Example:

![Screenshot 2023-09-14 at 13 09 30](https://github.com/frappe/books/assets/29507195/7c497d4c-ab03-45f5-baa4-e3de0680e527)

**Comment by akshayitzme** [comment]
Couldn't reproduce the issue, please reopen it if the issue persists.
