### ISSUE TITLE
(Open)There is no CRM Option ?? At least add Sime CRM like lead Client management with their Purchased details synced automatically

### ISSUE THREAD

**Issue by DancingRain12** [frappe/books#721]
Hello,

This is my first post, please bear with me. I just saw your App and itsssssss just FUU%%king amazing ..mind mind-blowing.
I just have one request, please

Why there is no CRM Option ?? 
1. At least add Sime CRM like lead **Client management** with their **Purchased details synced automatically** and W**e can attach notes to the client**. We can also **search** all that. Something like that

2. The best thing will be a **Note-taking module and Mind map-creating module**.

My kind request Add Simple CRM
Please Sir add this in upcoming updates.

**Comment by 18alantom** [comment]
@DancingRain12 thank you! The reason we haven't added a CRM is because it's a bit out of scope for an accounting application which is what Frappe Books is.

In adding features such as these it tends towards an ERP. In that case you could use ERPNext which [has these features](https://frappe.school/courses/erpnext-sales-crm/learn/1.1) or wait for [Frappe CRM](https://github.com/frappe/crm) to be built.

Closing this as request is out of scope.

**Comment by DancingRain12** [comment]
Can't we ADD A SIMPLE CRM like lead management or just people selection with notes?
Just a **Very Simple CRM** and **Note-taking or Mindmap**
**This will be the best Book software Sir...if this thing is added............ERP Next is an Ultimate solution but complicated but Frappe Book is THE BEST for ANYONE.**
My kindly request
Just add a **very Simple CRM**..

1.  Can ERP NEXT have a desktop version, Sir ??? 
2. And can we install any **plugins or addons** (If yes, where we can download that)   in FrappeBook for more tool?
Please reply sir
Thank you so much for building such a mind-blowing app
