### ISSUE TITLE
🐛 [Bug] - Profit and Loss Graph breaking on dashboard

### ISSUE THREAD

**Issue by njmulsqb** [frappe/books#820]
### Expected Behavior

It should stay within the axis like for filter "this year"
<img width="622" alt="image" src="https://github.com/frappe/books/assets/47940898/a67df4fe-e112-45d0-972a-1187c5721a98">

### Current Behavior

P&L graph is going out of axis in dashboard when "Year to Date" is selected
<img width="624" alt="image" src="https://github.com/frappe/books/assets/47940898/859e307f-5aa8-4d4f-9f76-9a37bf8a2fb4">

### FrappeBooks Version

0.20.1

### Path or Feature name

Dashboard

### Country

Pk

### Language

EN

### OS

Macos (Apple Silicon)

**Comment by njmulsqb** [comment]
![image](https://github.com/frappe/books/assets/47940898/fd528e64-9e38-473c-b241-d03fa751bb04)
Errors errors all the way. Miscalculated values and broken graphs, frappe seems to be in trouble recently

**Comment by Isaac-GC** [comment]
Unfortunately, in this case, it looks like this issue has been around for a while and has been hiding. It was fixed in https://github.com/frappe/books/pull/821 and in the latest version of Frappe Books

What happened is that the backend logic tries to figure out how to arrange and count the items needed for the graphs. In doing so, it subtracts 1 from a count and then divides by that subsequent value. As "Year to Date" starts with January, there will only be one item collected, and when 1 is subtracted from the items collected, there is 0 items/results remaining. That value (0) will be used in the denominator to try and divide by 0... which resulted in those (excessive) errors

Note: The line graph may look empty in the latest update, but the values are there and as soon as we hit February 1st (next Thursday), the line graph will show up as expected. The reason they don't show up *now* is that there is only one set of values for each of the profit and loss points, and when February hits, you'll have two sets of values each which will show up as expected. 
This has been part of the design since the feature had been added. IMO, it should be updated so if there is only set of values, you can at least see them on the graph. --> this will likely be in a future feature update
