### ISSUE TITLE
Auto-Update made all (Sales and Purchase) Payments disappear

### ISSUE THREAD

**Issue by raul-castillo** [frappe/books#838]
<h2>Auto-Update made all (Sales and Purchase) Payments disappear</h2>
Opened up Books today, there was an auto-update. After restarting the app, when I click on Purchase Payments or Sales Payments, it just appears empty.

![image](https://github.com/frappe/books/assets/67699453/8b4fe268-0b95-4e59-b932-cbf0ae0d67b5)

<h2>Info</h2>

**Version**: `0.21.1`
**Platform**: `win32`
**Path**: `/list/Payment/Purchase Payments?filters={%22referenceType%22:%22PurchaseInvoice%22}`
**Language**: `-`
**Country**: `in`

**Comment by Isaac-GC** [comment]
I believe this may be related to the v0.19.0 to v0.20.0 update. A patch for this issue was released in v0.20.1 (https://github.com/frappe/books/releases/tag/v0.20.1) for it.

Could you please try downloading and installing v0.20.1?   It should on startup fix the DB issue and you should see the payments again (and when prompted to update to the latest version again, the changes will carry over)

**Comment by raul-castillo** [comment]
Thank you for your help, Isaac!

This bug has been fixed for me with the next auto-update.
