### ISSUE TITLE
🐛 [Bug] - Purchase Payment Bug on Both Party

### ISSUE THREAD

**Issue by smalldale** [frappe/books#860]
### Expected Behavior

Purchase Payment `From Account` should use the same `From Account` from single role party.
![image](https://github.com/frappe/books/assets/49019693/baad4712-40e0-447d-b3e0-455ba1b40ea9)
![image](https://github.com/frappe/books/assets/49019693/9c0cf3c7-98c4-455d-a69f-42e9a9fb2dc5)

### Current Behavior

By default, it uses _Piutang Dagang Dalam Negeri_, with the options _Piutang Lain-lain_ and _Piutang Dagang_. Same if choose Transfer as `Payment Method`.
![image](https://github.com/frappe/books/assets/49019693/2c358197-86ff-4957-b214-e0cade15c20f)
![image](https://github.com/frappe/books/assets/49019693/c364b02f-f651-40bd-bdd8-ea030b6fac88)

### Steps to Reproduce

1. Create New Company. Add 2 Suppliers, and an Item.
I create a company like the screenshot below. 
![image](https://github.com/frappe/books/assets/49019693/a1148942-20b6-4c44-9219-90d32a6ab10b)
Create 2 party, one with only supplier role and other with both roles.
For Item is Pencil like the screenshot below.
![image](https://github.com/frappe/books/assets/49019693/58f95975-f915-4e32-bb98-cde7094a860f)
3. Create a new purchase invoice for both role like this, submit it, then create new payment.
![image](https://github.com/frappe/books/assets/49019693/2c358197-86ff-4957-b214-e0cade15c20f)

As comparison, create a new purchase invoice for single role (supplier), submit it, then create new payment.

### FrappeBooks Version

from 0.20.0 to 0.21.2

### Path or Feature name

Purchase Invoice

### Country

ID

### Language

EN

### OS

Windows 10

**Comment by Sutiksh27** [comment]
Hello, I am trying to solve this bug, just wanted to make sure, the From account that we can see in the payment section side should be similar to the account we have chosen while creating the single role party or both role party, right?

**Comment by Abhi135721** [comment]
Hi, I am trying to resolve this bug as well. I think that is the requirement @Sutiksh27. 

I found out that when a party is created with both role and when we try to add payment, the payment type is marked as Receive even if it is a Purchase invoice. Is it expected behavior or do we need to change the payment type based on whether it is a Purchase/Sales invoice?

**Comment by Sutiksh27** [comment]
> Hi, I am trying to resolve this bug as well. I think that is the requirement @Sutiksh27.
> 
> I found out that when a party is created with both role and when we try to add payment, the payment type is marked as Receive even if it is a Purchase invoice. Is it expected behavior or do we need to change the payment type based on whether it is a Purchase/Sales invoice?

In this particular issue, we only need to change the account that we can view in the payment section dropdown to the one assigned to the single role party/both parties. I can't see the payment type as Receive for both parties, can you share how did you arrive to that scenario?

**Comment by Abhi135721** [comment]
1. I created a Purchase invoice with Supplier set as Party with both role:
![image](https://github.com/frappe/books/assets/28592190/2ec93442-554f-43e4-b4e9-212f2d03368b)

2. Then, I tried to add payment and I can see the payment type as *Receive* here:
![image](https://github.com/frappe/books/assets/28592190/f6de0fc3-778e-46e4-96e4-5722992706d4)

3. I think, when the payment type is set to receive, accounts also change from when the payment type was set to pay. I might be wrong here. Just trying to understand if this is the expected behavior.

**Comment by Sutiksh27** [comment]
I think it should be pay, When I tried to save a payment, it says the amount was paid from the "from account" to the "account" which you can see on the invoice side. That's what I was asking previously, because it is confusing based on the output that I am receiving.

**Comment by Abhi135721** [comment]
Yeah, I think it should be pay too. If it is pay, then I guess the issue will be solved because the accounts change. But I am not sure if  it was expected behavior or changing it to pay effects some other flow. So, wanted to confirm here.
