### ISSUE TITLE
🐛 [General Question] - Is intel build for macOS ended?

### ISSUE THREAD

**Issue by daeho-ro** [frappe/books#936]
### Summary

Hello,

I am just curious about the version 0.22 only releases `arm` for macOS. Is `intel` version stop released?

Thanks,

- https://github.com/Homebrew/homebrew-cask/pull/183964

**Comment by rtdany10** [comment]
@akshayitzme @AbleKSaju

**Comment by wasabinetwork** [comment]
I would also like to know if support for Intel-based Macs has ended.

**Comment by 18alantom** [comment]
I suspect this is due to the the Publish GitHub action ([ref](https://github.com/frappe/books/blob/1e41c0803cdba2161034253479bedd433347c8dd/.github/workflows/publish.yml#L7)) running on the `macos-latest` runner.

This points to a macOS 14 ARM image ([ref](https://github.com/actions/runner-images)) causing the built Frappe Books to be an ARM one. Adding another runner (eg: `macos-14-large`) to the `publish.yml` should generate the Intel ones again.

**Comment by system19** [comment]
@18alantom 
Sounds like a simple fix for the maintainer. Would be great to have a Intel-based Mac installer again.

**Comment by akshayitzme** [comment]
fixed in #991. 
Intel builds for MacOS will be back again from the next release.
